# Generated by Django 4.2.7 on 2023-11-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urltofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdffilename', models.TextField(blank=True, null=True)),
                ('pdfurl', models.URLField(blank=True)),
                ('pdffilepath', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
