# Generated by Django 4.1.2 on 2024-01-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftodxf', '0002_urltofile_dxffilepath_urltofile_dxfurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdftodxffile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdffilename', models.TextField(blank=True, null=True)),
                ('pdfurl', models.URLField(blank=True)),
                ('pdffilepath', models.TextField(blank=True, null=True)),
                ('dxffilepath', models.TextField(blank=True, null=True)),
                ('dxfurl', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
