# Generated by Django 4.2.7 on 2023-11-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdftodxf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urltofile',
            name='dxffilepath',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urltofile',
            name='dxfurl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
