# Generated by Django 4.1.2 on 2024-03-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='htmltopdffile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htmlfilename', models.TextField(blank=True, null=True)),
                ('htmlurl', models.URLField(blank=True)),
                ('htmlfilepath', models.TextField(blank=True, null=True)),
                ('pdffilepath', models.TextField(blank=True, null=True)),
                ('pdfurl', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
